### ISSUE TITLE
License questions/problems

### ISSUE THREAD

**Issue by FrederikP** [aspecto-io/sns-sqs-big-payload#27]
Hi there, 
as you can see I started using your library and extending your library https://github.com/aspecto-io/sns-sqs-big-payload/pull/26

I looked into the license, because I thought some of the consumer interface/options/code is kind of similar to the bbc consumer: https://github.com/bbc/sqs-consumer

If you took some of the code to start with this project maybe you should consider stating that in the README or maybe it would even be needed to actually include their license, or at least their lines in your license file.
```
Copyright (c) 2017-present British Broadcasting Corporation

All rights reserved

(http://www.bbc.co.uk) and sqs-consumer Contributors
```

But maybe you just randomly have a very similar naming of options and stuff because it's obviously derived from the same aws docs.

Nonetheless, looking at your license file I'm seeing:

```
Copyright [yyyy] [name of copyright owner]
```

1. You only need to include the part of the license starting with that line
2. You should actually add year and owner information

I wasn't sure if I should even open up this issue, because I don't care too much personally. But I thought if more and more people start using it, you might want to know about this, so you can clean it up.

Cheers and thanks for the great library.

**Comment by mzahor** [comment]
I looked into that library as we were building essentially the same thing, just with large payload feature and maybe a few other things, but I don't remember copying any code. So, I think mentioning it in the readme should be enough. Thanks for pointing out.
